CREATE TABLE IF NOT EXISTS songs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(64) NULL,
  slug VARCHAR(255) NOT NULL,
  page_url VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  artists_json JSON NULL,
  artists_text VARCHAR(500) NULL,
  genres_json JSON NULL,
  genres_text VARCHAR(500) NULL,
  versions_json JSON NULL,
  cover_thumb_url TEXT NULL,
  cover_medium_url TEXT NULL,
  cover_large_url TEXT NULL,
  audio_url TEXT NULL,
  preview_seconds INT NULL,
  release_date DATE NULL,
  description TEXT NULL,
  attribution_text TEXT NULL,
  download_path VARCHAR(255) NULL,
  youtube_watch_url VARCHAR(255) NULL,
  source_hash CHAR(64) NULL,
  first_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_slug (slug),
  UNIQUE KEY uniq_external_id (external_id),
  KEY idx_release_date (release_date),
  KEY idx_title (title),
  KEY idx_artists_text (artists_text(191)),
  KEY idx_genres_text (genres_text(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crawl_runs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  mode VARCHAR(50) NOT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'running',
  pages_crawled INT NOT NULL DEFAULT 0,
  detail_pages_crawled INT NOT NULL DEFAULT 0,
  songs_seen INT NOT NULL DEFAULT 0,
  songs_upserted INT NOT NULL DEFAULT 0,
  message TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
